solve task 1
Fenya2/Robots_OOP_Course pull request #2
Opened 2024-02-20 04:08 UTC by Fenya2

Добавил диалог с подтверждением закрытия программы на русском языке.
Выделил логику создания строки меню в отдельный класс MainMenuBar

2024-02-26 18:02 UTC, vpyzhyanov requested changes
В целом решение очень хорошее, но есть некоторые замечания.

2024-02-26 18:02 UTC, vpyzhyanov commented on src/main/java/course/oop/gui/MainApplicationFrame.java
> +        setBounds(inset, inset, screenSize.width, screenSize.height);
Вы уверены, что хотите это поменять? Какую цель вы преследуете?

2024-02-26 18:02 UTC, vpyzhyanov commented on src/main/java/course/oop/gui/MainApplicationFrame.java
> +        gameWindow.setBounds(300, 0, 800, 800);
И это тоже интересно зачем

2024-02-26 18:02 UTC, vpyzhyanov commented on src/main/java/course/oop/gui/MainApplicationFrame.java
> +    protected LogWindow createLogWindow() {
Вижу, что вы просто перенесли эти методы. Но раз вы это сделали, непонятно зачем, то будет вам замечание за это (чтобы неповадно было затирать историю изменений в Git):

Обоснуйте необходимость именно такого модификатора доступа.

2024-02-26 18:02 UTC, vpyzhyanov commented on src/main/java/course/oop/gui/MainMenuBar.java
> +public class MainMenuBar extends JMenuBar {
Отсутствует описание класса

2024-02-26 18:02 UTC, vpyzhyanov commented on src/main/java/course/oop/gui/MainMenuBar.java
> +    private JMenu generateViewModeMenu() {
слово generate не очень удачное, т.к. вы ничего не генерируете, вы создаёте. Даже сами это в описании пишете. Генерируют случайные числа, а не элементы меню. Тут лучше слово create

2024-02-26 18:02 UTC, vpyzhyanov commented on src/main/java/course/oop/gui/MainMenuBar.java
> +        JMenuItem quitItem = new JMenuItem("Выход", KeyEvent.VK_S);
почему S?

2024-02-26 18:02 UTC, vpyzhyanov commented on src/main/java/course/oop/gui/RobotsProgram.java
> -        frame.pack();
зачем это убирать?

2024-02-27 15:13 UTC, Fenya2 commented on src/main/java/course/oop/gui/MainApplicationFrame.java
> +        setBounds(inset, inset, screenSize.width, screenSize.height);
Я преследовал цель "пощупать" проект. Забыл откатить состояние файла до изначального перед написанием кода. Хотя учитывая второе задание, параметры setBounds все равно придется изменять. Пожалуй такое положение окон по умолчанию выгоднее, чем изначальное, где окна накладываются друг на друга. Хотя это наверное мешает проверять код?

2024-02-27 15:13 UTC, Fenya2 commented on src/main/java/course/oop/gui/MainApplicationFrame.java
> +        gameWindow.setBounds(300, 0, 800, 800);
Та же причина

2024-02-27 15:13 UTC, Fenya2 commented on src/main/java/course/oop/gui/MainApplicationFrame.java
> +    protected LogWindow createLogWindow() {
Да, это случайно вышло. Такие модификаторы доступа оставил Александр Владимирович. Мне здесь более уместными кажутся модификаторы доступа private.

2024-02-27 15:13 UTC, Fenya2 commented on src/main/java/course/oop/gui/MainMenuBar.java
> +public class MainMenuBar extends JMenuBar {
Добавлю

2024-02-27 15:14 UTC, Fenya2 commented on src/main/java/course/oop/gui/MainMenuBar.java
> +    private JMenu generateViewModeMenu() {
Понял

2024-02-27 15:14 UTC, Fenya2 commented on src/main/java/course/oop/gui/MainMenuBar.java
> +        JMenuItem quitItem = new JMenuItem("Выход", KeyEvent.VK_S);
Изменю на более удачные мнемоники

2024-02-27 15:17 UTC, Fenya2 commented on src/main/java/course/oop/gui/RobotsProgram.java
> -        frame.pack();
Он, как и следующая за ним инструкция frame.setExtendedState(Frame.MAXIMIZED_BOTH) был лишним. Как и сам setExtendedState(Frame.MAXIMIZED_BOTH), ведь в самом конструкторе MainApplicationFrame задавался третий размер. Сделаю размер главного окна по умолчанию, как написано в описании конструктора - с отступами по 50 пикселей

2024-02-27 15:29 UTC, Fenya2 commented on src/main/java/course/oop/gui/RobotsProgram.java
> +}
Блин, опять. Как это контролировать?

2024-02-27 15:30 UTC, Fenya2 commented on src/main/java/course/oop/gui/RobotsProgram.java
> +}
Ладно, я понял. Простите

2024-02-28 18:58 UTC, vpyzhyanov commented on src/main/java/course/oop/gui/MainApplicationFrame.java
> +        setBounds(inset, inset, screenSize.width, screenSize.height);
Нет не помешает. Всё хорошо, главное когда вы чётко знаете цель)

2024-02-28 18:59 UTC, vpyzhyanov commented on src/main/java/course/oop/gui/MainApplicationFrame.java
> +    protected LogWindow createLogWindow() {
в таком случае поменяйте на private

2024-02-28 19:01 UTC, vpyzhyanov commented on src/main/java/course/oop/gui/RobotsProgram.java
> -        frame.pack();
Вообще-то pack() отвечает не только за размер текущего окна, но и всех его дочерних окон.

2024-02-28 19:04 UTC, vpyzhyanov approved these changes

2024-02-28 19:04 UTC, vpyzhyanov commented on src/main/java/course/oop/gui/MainApplicationFrame.java
> + * Следует разделить его на серию более простых методов (или вообще выделить
разве вы это не сделали? Почему комментарий не убрали?

2024-02-28 19:06 UTC, vpyzhyanov commented
после исправления оставшихся замечаний, можете мёрджить

2024-02-28 19:18 UTC, vpyzhyanov commented on src/main/java/course/oop/gui/MainApplicationFrame.java
> +    protected LogWindow createLogWindow() {
Исходное замечание про перенос методов не исправлено!!!!

2024-02-28 19:20 UTC, vpyzhyanov requested changes

2024-02-28 19:20 UTC, vpyzhyanov commented on src/main/java/course/oop/gui/MainApplicationFrame.java
> +    public void setLookAndFeel(String className) {
1. Из-за изменения порядка метода теперь это "новый" код. Значит пишите JavaDoc к нему
2. Этот метод должен быть private. Вы тут нарушили ООП этим публичным доступом. Подумайте что именно вы нарушили и придумайте как сделать его private

2024-02-29 18:43 UTC, Fenya2 commented on src/main/java/course/oop/gui/MainApplicationFrame.java
> +        setBounds(inset, inset, screenSize.width, screenSize.height);
Понял

2024-02-29 18:43 UTC, Fenya2 commented on src/main/java/course/oop/gui/MainApplicationFrame.java
> +    protected LogWindow createLogWindow() {
Какое замечание? Я не понял. Если я их снова подниму наверх, git снова посчитает их на новые методы

2024-02-29 18:43 UTC, Fenya2 commented on src/main/java/course/oop/gui/RobotsProgram.java
> -        frame.pack();
С pack() какая-то беда. Если я вызываю его в конце конструктора, он сворачивает окно до микроскопического вида. Я не знаю, с чем это связано пока

2024-02-29 18:43 UTC, Fenya2 commented on src/main/java/course/oop/gui/MainApplicationFrame.java
> + * Следует разделить его на серию более простых методов (или вообще выделить
Уберу

2024-02-29 18:44 UTC, Fenya2 commented on src/main/java/course/oop/gui/MainApplicationFrame.java
> +    public void setLookAndFeel(String className) {
Напишу javadoc, добавлю классу MainApplicationFrame 2 публичных метода, которые и будут вызываться в MainMenuBar при нажатии соответсвующих пунктов меню

2024-03-01 18:27 UTC, merged