Task2
Fenya2/Robots_OOP_Course pull request #3
Opened 2024-03-10 18:14 UTC by Fenya2

Выполнил задачу 2:
При обработке события закрытия главного окна состояния окон сохраняются в файл.
При повторном запуске приложения состояния окон восстанавливаются (берутся из файла, куда были сохранены).
Файл с конфигурацией windowStates.conf создается в домашнем каталоге пользователя, в подкаталоге {user.home}/Robots/config/

2024-03-22 15:14 UTC, Fenya2 commented
- Убрал синглтон, вместо него два класса: FrameSaver и FrameLoader
- awt классы не сериализуются, вместо них Pair, в который они преобразуются.
- Тесты пишут во временную директорию (аннотация Rule в паре с классом TemporaryFolder)
- Чтобы избежать дублирования кода при реализации интерфейса Saveable, в паре с ним используется SaveableDelegate, которому делегируются операции сохранения  (?Но там много if для проверки экземпляра. Это норм?)

2024-03-25 17:36 UTC, vpyzhyanov requested changes
есть замечания

2024-03-25 17:36 UTC, vpyzhyanov commented on src/main/java/course/oop/gui/GameWindow.java
> +        return saveableDelegate.getFrameId();
Тут 2 объекта, которые решают одну задачу. 1 - текущий класс, 2 - ваш делегат. Ответственность за имя формы вы отдали делегату, но здесь почему-то ещё раз к ней обращаетесь. Отсюда вопрос: а точно ли делегат должен отвечать за имя компоненты? Точно нужна куча делегатов для каждой компоненты?

Во всех случаях ответ нет. Делегирование здесь не самый удачный выбор, т.е. его задача просто перевести компоненту в свойства для сохранения. Знать что-то о компоненте ему вообще не обязательно. 

Вообще-то я имел в виду, что один класс должен отвечать и за сохранение состояния и за конвертацию компонента. Либо это может быть утилитарный класс на худой конец (но это тоже не очень, т.к. использоваться он будет **только в одном месте**).

2024-03-25 17:36 UTC, vpyzhyanov commented on src/main/java/course/oop/gui/GameWindow.java
> +    public FrameConfig getWindowConfig() {
На самом деле единственный реально нужный метод интерфейса Saveble - это getFrameId, остальные не нужны. Непосредственно при сохранении можно достать все нужные свойства.

2024-03-25 17:36 UTC, vpyzhyanov commented on src/main/java/course/oop/gui/LogWindow.java
> +        return saveableDelegate.getFrameId();
ещё раз, на всякий случай: как понять, что метод не нужен? Если он тупо передаёт информацию другому классу, но при этом использует эту информацию тоже только он. Значит её точно не надо гонять лишний раз. Имя компонента сфомировано в компоненте, потом ушло в делегат, а достаёт его только этот же самый компонент.

2024-03-25 17:36 UTC, vpyzhyanov commented on src/main/java/course/oop/gui/MainApplicationFrame.java
> +    private final List<Component> childs;
В смысле убивает? При сворачивании? Не забудьте показать мне это на паре в живую, пожалуйста.

А так это пока дублирование функционала.

2024-03-25 17:36 UTC, vpyzhyanov commented on src/main/java/course/oop/gui/MainApplicationFrame.java
> +    private final JDesktopPane desktopPane;
определяете поле, которое уже есть в этом классе. Можно получить через `getContentPane()`

2024-03-25 17:36 UTC, vpyzhyanov commented on src/main/java/course/oop/gui/MainApplicationFrame.java
> +    private final SaveableDelegate saveableDelegate;
аналогично, тут этот класс не нужен

2024-03-25 17:36 UTC, vpyzhyanov commented on src/main/java/course/oop/gui/MainApplicationFrame.java
> +        for (Component c : childs)
так себе затея пробегаться только по тем, которые вы сами сохранили. Компоненты могут добавляться в других классах и вы этого даже не заметите. Системную логику переопределять не стоит.

2024-03-25 17:36 UTC, vpyzhyanov commented on src/main/java/course/oop/gui/MainApplicationFrame.java
> +            if (c instanceof Saveable)
однобуквенные имена - это ужасно. Никогда, кроме счётчиков, их не используйте. А скатитесь до a, b, c. Одно слово не так уж и сложно написать, особенно с учётом автодополнения в IDEA.

2024-03-25 17:36 UTC, vpyzhyanov commented on src/main/java/course/oop/gui/MainApplicationFrame.java
> +        FrameLoader fl = new FrameLoader();
тоже имя оставляет желать лучшего

2024-03-25 17:36 UTC, vpyzhyanov commented on src/main/java/course/oop/gui/MainApplicationFrame.java
> +    private void paintFrames() {
неудачное название. Paint - это стандартный метод, который занимается **рисованием**. А у вас просто сделать компонент видимым. Ничего вы не рисуете, это делают другие методы!

Да и зачем вообще выносить видимость отдельно? Окна дёргаются? Вроде не должны успевать

2024-03-25 17:36 UTC, vpyzhyanov commented on src/main/java/course/oop/gui/RobotsProgram.java
> +      new FrameSaver().initHierachy(); // создание конфигурационного файла, если его еще нет.
ой, что это? Зачем? Не надо так делать, пожалуйста. Какой-то "левый" функционал находится на старте приложения и диктует свои правила, притом непонятно какие и непонятно зачем.

2024-03-25 17:36 UTC, vpyzhyanov commented on src/main/java/course/oop/saving/FrameConfig.java
> +    private boolean isIcon;
вам разве IDEA не подсказывает, что надо сделать поля final?

2024-03-25 17:36 UTC, vpyzhyanov commented on src/main/java/course/oop/saving/FrameConfig.java
> +     * Геттер
класс))) Очень понятно и информативно)))

2024-03-25 17:36 UTC, vpyzhyanov commented on src/main/java/course/oop/saving/FrameConfig.java
> +     * Геттер
И не поспоришь ведь)))))

2024-03-25 17:36 UTC, vpyzhyanov commented on src/main/java/course/oop/saving/FrameConfig.java
> +     * Геттер
хотя я придумал описание лучше "метод"))))

А если серьёзно, то напишите названия свойств на русском языке в JavaDoc для самих полей. Они сразу распространяться и на методы.

2024-03-25 17:36 UTC, vpyzhyanov commented on src/main/java/course/oop/saving/FrameConfig.java
> +    public String toStringFormatted() {
то что вы пишете - это обычный toString(), поэтому не надо тут ничего изобретать. Похоже вы не поняли смысл форматированных строк ((((

2024-03-25 17:36 UTC, vpyzhyanov commented on src/main/java/course/oop/saving/FrameSaveLoader.java
> +public abstract class FrameSaveLoader {
добро пожаловать на тёмную сторону ООП: бессмысленное и беспощадное создание никому не нужных абстракций. Я же говорил, что если вы хотите решить проблему дублирования через наследование, то забудьте об этом раз и навсегда, выберите другой путь.

На самом деле само существование этого класса должно было вас натолкнуть на мысль, что идея делать сохранение и загрузку - не самая лучшая. Эти классы работают с **единым ресурсом**, поэтому должны быть **единым классом**.

2024-03-25 17:36 UTC, vpyzhyanov commented on src/main/java/course/oop/saving/FrameSaveLoader.java
> +    protected Map<String, FrameConfig> states;
protected - фу)))

2024-03-25 17:36 UTC, vpyzhyanov commented on src/main/java/course/oop/saving/FrameSaveLoader.java
> +     * Геттер
опять идеальные описания

2024-03-25 17:36 UTC, vpyzhyanov commented on src/main/java/course/oop/saving/FrameSaveLoader.java
> +    public void setConfilename(String confilename) {
имя очень странное, я не могу его расшифровать

2024-03-25 17:36 UTC, vpyzhyanov commented on src/main/java/course/oop/saving/FrameSaveLoader.java
> +        confilename = "windowStates.conf";
лишнее свойство. У вас же есть saveLocation, почему его не хватило? это же **ФАЙЛ** (File)! В общем confilename нужно удалить как избыточное

2024-03-25 17:36 UTC, vpyzhyanov commented on src/main/java/course/oop/saving/FrameSaver.java
> + * используя методы setSaveLocation, setConfilename</li>
вот видите, вы же сами пишете, что эти ДВА метода отвечают за одно и то же. Почему тогда их 2, а не 1?

2024-03-25 17:36 UTC, vpyzhyanov commented on src/main/java/course/oop/saving/FrameSaver.java
> +                os.close();
это норм, но привыкайте лучше к хорошему, используйте try-with-resources

2024-03-25 17:36 UTC, vpyzhyanov commented on src/main/java/course/oop/saving/FrameSaver.java
> +            save(new HashMap<String, FrameConfig>());
даже глядя на реализацию непонятно зачем это надо. Тем более непонятно зачем сохранять пустой конфиг.

2024-03-25 17:36 UTC, vpyzhyanov commented on src/main/java/course/oop/saving/Pair.java
> +    public String toStringFormatted() {
это обычный toString()

2024-03-25 17:36 UTC, vpyzhyanov commented on src/main/java/course/oop/saving/Saveable.java
> +    String getFrameId();
единственный нужный метод

2024-03-25 17:36 UTC, vpyzhyanov commented on src/main/java/course/oop/saving/SaveableDelegate.java
> +            this.id = id;
вы разве не видите, что оба действия абсолютно одинаковые? Зачем тогда if?

2024-03-25 17:36 UTC, vpyzhyanov commented on src/main/java/course/oop/saving/SaveableDelegate.java
> +    private final Component c;
не сложно написать одно слово. Однобуквенные имена - зло (кроме индексов)

2024-03-25 17:36 UTC, vpyzhyanov commented on src/main/java/course/oop/saving/SaveableDelegate.java
> +            JFrame jf = (JFrame) c;
Это можно писать удобнее:
![image](https://github.com/Fenya2/Robots_OOP_Course/assets/71599019/9b8038cb-10ef-4a6f-af24-568ea9791c97)

2024-03-25 17:36 UTC, vpyzhyanov commented on src/main/java/course/oop/saving/SaveableDelegate.java
> +            return new FrameConfig(jf.getSize(), jf.getLocation(), false);
вы совсем не смотрите методы какого интерфейсы вы используете? А следовало бы, тогда и код станет намного проще. Это класс `Component`, который является общим абсолютно для всех компонент. Следовательно на instanceof можно не проверять, а сразу работать с типом `Component`. Я имею в виду в поле определить именно этот тип.

2024-03-25 17:36 UTC, vpyzhyanov commented on src/main/java/course/oop/saving/SaveableDelegate.java
> +            jif.setLocation(config.getLocation().toPoint());
дублирование (я напоминаю, что интерфейс `Component` тут у всех общий)

2024-03-25 17:36 UTC, vpyzhyanov commented on src/test/java/course/oop/saving/FrameLoaderTest.java
> +        Assert.assertFalse(stub.saved == stub.loaded);
1. assertNotSame
2. А что вы тут вообще проверяете?
3. А ничего, что это условие полностью противоречит следующей проверке?

2024-03-25 17:36 UTC, vpyzhyanov commented on src/test/java/course/oop/saving/FrameLoaderTest.java
> +            Assert.assertTrue(false);
1. Assert.fail("**Понятное человекочитаемое сообщение**")
2. Зачем вообще в тестах try? Не надо его. Исключение уже завалит тест.

2024-03-25 17:36 UTC, vpyzhyanov commented on src/test/java/course/oop/saving/FrameLoaderTest.java
> +        FrameSaver fs = new FrameSaver();
Это не FrameLoaderTest, он проверяет сразу 2 класса, почему-то

2024-03-25 17:36 UTC, vpyzhyanov commented on src/test/java/course/oop/saving/FrameLoaderTest.java
> +        Assert.assertEquals(stub.saved, stub.loaded);
метод абсолютно ничего не проверяет. Как думаете почему?

2024-03-25 17:36 UTC, vpyzhyanov commented on src/test/java/course/oop/saving/FrameSaverTest.java
> +        FrameSaver fs = new FrameSaver();
весь класс - дубликат

2024-03-25 17:36 UTC, vpyzhyanov commented on src/test/java/course/oop/saving/FrameSaverTest.java
> +                Assert.assertEquals(ss.saved, actual.get("tmp_w"));
вот тут что-то похожее на реальную проверку

2024-03-25 22:02 UTC, Fenya2 commented on src/main/java/course/oop/gui/GameWindow.java
> +        return saveableDelegate.getFrameId();
Вроде понял. Перенес логигу класса-делегата в FrameStatesManager

2024-03-25 22:02 UTC, Fenya2 commented on src/main/java/course/oop/gui/GameWindow.java
> +    public FrameConfig getWindowConfig() {
Оставил только один метод в интерфейсе Saveable

2024-03-25 22:03 UTC, Fenya2 commented on src/main/java/course/oop/gui/LogWindow.java
> +        return saveableDelegate.getFrameId();
Теперь компоненты сразу возвращают строку, не обращаясь к делегату

2024-03-25 22:03 UTC, Fenya2 commented on src/main/java/course/oop/gui/MainApplicationFrame.java
> +    private final List<Component> childs;
Сделал локальную ветку с демонстрацией

2024-03-25 22:03 UTC, Fenya2 commented on src/main/java/course/oop/gui/MainApplicationFrame.java
> +    private final JDesktopPane desktopPane;
Убрал поле

2024-03-25 22:03 UTC, Fenya2 commented on src/main/java/course/oop/gui/MainApplicationFrame.java
> +    private final SaveableDelegate saveableDelegate;
Убрал

2024-03-25 22:03 UTC, Fenya2 commented on src/main/java/course/oop/gui/MainApplicationFrame.java
> +        for (Component c : childs)
Как будто у свернутых окон слетает интерфейс Saveable, поэтому этот костыль с childs

2024-03-25 22:03 UTC, Fenya2 commented on src/main/java/course/oop/gui/MainApplicationFrame.java
> +            if (c instanceof Saveable)
Переименовал

2024-03-25 22:04 UTC, Fenya2 commented on src/main/java/course/oop/gui/MainApplicationFrame.java
> +        FrameLoader fl = new FrameLoader();
Переименовал

2024-03-25 22:04 UTC, Fenya2 commented on src/main/java/course/oop/gui/MainApplicationFrame.java
> +    private void paintFrames() {
Да, не дергаются)

2024-03-25 22:04 UTC, Fenya2 commented on src/main/java/course/oop/gui/RobotsProgram.java
> +      new FrameSaver().initHierachy(); // создание конфигурационного файла, если его еще нет.
Убрал

2024-03-25 22:04 UTC, Fenya2 commented on src/main/java/course/oop/saving/FrameConfig.java
> +    private boolean isIcon;
Не подсказывает. Надо настроить

2024-03-25 22:04 UTC, Fenya2 commented on src/main/java/course/oop/saving/FrameConfig.java
> +     * Геттер
^_^

2024-03-25 22:04 UTC, Fenya2 commented on src/main/java/course/oop/saving/FrameConfig.java
> +     * Геттер
Не совсем понял

2024-03-25 22:05 UTC, Fenya2 commented on src/main/java/course/oop/saving/FrameConfig.java
> +    public String toStringFormatted() {
Теперь понял. Переопределил toString Object-а

2024-03-25 22:05 UTC, Fenya2 commented on src/main/java/course/oop/saving/FrameSaveLoader.java
> +public abstract class FrameSaveLoader {
Понял. Сделал FrameStatesManager

2024-03-25 22:06 UTC, Fenya2 commented on src/main/java/course/oop/saving/FrameSaveLoader.java
> +    protected Map<String, FrameConfig> states;
Убрал абстрактный класс

2024-03-25 22:06 UTC, Fenya2 commented on src/main/java/course/oop/saving/FrameSaveLoader.java
> +     * Геттер
:)

2024-03-25 22:06 UTC, Fenya2 commented on src/main/java/course/oop/saving/FrameSaveLoader.java
> +    public void setConfilename(String confilename) {
Переименовал

2024-03-25 22:06 UTC, Fenya2 commented on src/main/java/course/oop/saving/FrameSaveLoader.java
> +        confilename = "windowStates.conf";
Сделал одно поле File

2024-03-25 22:06 UTC, Fenya2 commented on src/main/java/course/oop/saving/FrameSaver.java
> + * используя методы setSaveLocation, setConfilename</li>
Вынес в один класс

2024-03-25 22:07 UTC, Fenya2 commented on src/main/java/course/oop/saving/FrameSaver.java
> +                os.close();
Переписал

2024-03-25 22:07 UTC, Fenya2 commented on src/main/java/course/oop/saving/FrameSaver.java
> +            save(new HashMap<String, FrameConfig>());
Убрал

2024-03-25 22:07 UTC, Fenya2 commented on src/main/java/course/oop/saving/Pair.java
> +    public String toStringFormatted() {
Переопределил

2024-03-25 22:07 UTC, Fenya2 commented on src/main/java/course/oop/saving/Saveable.java
> +    String getFrameId();
Оставил только его

2024-03-25 22:07 UTC, Fenya2 commented on src/main/java/course/oop/saving/SaveableDelegate.java
> +            this.id = id;
Убрал этот класс вовсе

2024-03-25 22:08 UTC, Fenya2 commented on src/main/java/course/oop/saving/SaveableDelegate.java
> +    private final Component c;
Убрал

2024-03-25 22:08 UTC, Fenya2 commented on src/main/java/course/oop/saving/SaveableDelegate.java
> +            JFrame jf = (JFrame) c;
Перепиисал

2024-03-25 22:09 UTC, Fenya2 commented on src/main/java/course/oop/saving/SaveableDelegate.java
> +            return new FrameConfig(jf.getSize(), jf.getLocation(), false);
Понял

2024-03-25 22:09 UTC, Fenya2 commented on src/main/java/course/oop/saving/SaveableDelegate.java
> +            jif.setLocation(config.getLocation().toPoint());
Точно

2024-03-25 22:11 UTC, Fenya2 commented on src/test/java/course/oop/saving/FrameSaverTest.java
> +        FrameSaver fs = new FrameSaver();
Объединил в один

2024-03-25 22:12 UTC, Fenya2 commented on src/test/java/course/oop/saving/FrameLoaderTest.java
> +        Assert.assertEquals(stub.saved, stub.loaded);
Забыл переопределить equals для заглушки. Убрал вообще заглушку

2024-03-25 22:12 UTC, Fenya2 commented on src/test/java/course/oop/saving/FrameLoaderTest.java
> +        FrameSaver fs = new FrameSaver();
Убрал тест для этого класса

2024-03-25 22:14 UTC, Fenya2 commented on src/test/java/course/oop/saving/FrameLoaderTest.java
> +            Assert.assertTrue(false);
Я вспомнил, что можно указать исключения в сигнатуре метода, чтобы компилятор не жаловался. Сделаю коммит

2024-03-25 22:14 UTC, Fenya2 commented on src/test/java/course/oop/saving/FrameSaverTest.java
> +                Assert.assertEquals(ss.saved, actual.get("tmp_w"));
Здорово)

2024-03-25 22:20 UTC, Fenya2 commented
Что-то исправил

2024-03-26 04:10 UTC, vpyzhyanov commented on src/main/java/course/oop/gui/MainApplicationFrame.java
> +        for (Component c : childs)
Интерфейс не может "слетать", это невозможно. Жду демонстрации.

Очень хорошо, что вы понимаете, что это костыль

2024-03-26 04:15 UTC, vpyzhyanov commented on src/main/java/course/oop/saving/FrameStatesManager.java
> +public class FrameStatesManager implements FrameSaver, FrameLoader {
Я посмотрел места использования, вы не используете эти интерфейсы. Их надо удалить за ненадобностью.

Интерфейсы нужны когда вы отделяете реализацию от контракта. В этом приложении вы всегда пользуетесь только реализацией. И это правильно.

2024-03-26 04:15 UTC, vpyzhyanov commented on src/main/java/course/oop/gui/MainApplicationFrame.java
> +        FrameLoader frameLoader = new FrameStatesManager();
нет никакой необходимости создавать этот класс по несколько раз. Можно вынести в поле класса с модификатором final

2024-03-26 04:15 UTC, vpyzhyanov commented on src/main/java/course/oop/saving/FrameConfig.java
> +    private boolean isIcon;
Наверное это Ultimate версия подсказывает

2024-03-26 04:16 UTC, vpyzhyanov commented on src/main/java/course/oop/saving/FrameConfig.java
> +     * Геттер
Не исправлено. Это был сарказм)

2024-03-26 04:16 UTC, vpyzhyanov commented on src/main/java/course/oop/saving/FrameConfig.java
> +     * Геттер
не исправлено

2024-03-26 04:18 UTC, vpyzhyanov commented on src/main/java/course/oop/saving/FrameConfig.java
> +     * Геттер
это был сарказм. Нужно сделать так:

```java
    /**
     * Свёрнутость
     */
    private final boolean isIcon;
```

А с геттеров JavaDoc убрать.

2024-03-26 04:19 UTC, vpyzhyanov commented on src/main/java/course/oop/saving/FrameSaveLoader.java
> +     * Геттер
не исправлено

2024-03-26 04:22 UTC, vpyzhyanov commented on src/main/java/course/oop/saving/SaveableDelegate.java
> +            this.id = id;
а саму проблему не исправили, т.к этот код просто перенесли в другой класс. Замечание по прежнему актуально.

2024-03-26 04:23 UTC, vpyzhyanov commented on src/main/java/course/oop/saving/SaveableDelegate.java
> +            return new FrameConfig(jf.getSize(), jf.getLocation(), false);
Точно поняли? что-то я не уверен в этом

![image](https://github.com/Fenya2/Robots_OOP_Course/assets/71599019/b7d33dea-8999-4692-93a1-76d23b235254)

2024-03-26 04:25 UTC, vpyzhyanov commented on src/main/java/course/oop/saving/SaveableDelegate.java
> +            return new FrameConfig(jf.getSize(), jf.getLocation(), false);
То есть чтобы не было методов `getFrameConfigForJFrame`, `getFrameConfigForJInternalFrame`. А был один метод. Тогда и код не будет дублироваться, как он делает сейчас

2024-03-26 04:26 UTC, vpyzhyanov commented on src/main/java/course/oop/saving/SaveableDelegate.java
> +            jif.setLocation(config.getLocation().toPoint());
не исправлено

2024-03-26 04:26 UTC, vpyzhyanov commented on src/test/java/course/oop/saving/FrameLoaderTest.java
> +        Assert.assertFalse(stub.saved == stub.loaded);
нет ответа

2024-03-26 04:27 UTC, vpyzhyanov commented on src/test/java/course/oop/saving/FrameLoaderTest.java
> +        Assert.assertEquals(stub.saved, stub.loaded);
нет, не поэтому

2024-03-26 04:31 UTC, vpyzhyanov requested changes

2024-03-26 04:31 UTC, vpyzhyanov commented on src/test/java/course/oop/saving/FrameStatesManagerTest.java
> +        is.close();
очень плохо, прям очень. Половину баллов надо за такое снимать

2024-03-26 04:31 UTC, vpyzhyanov commented on src/test/java/course/oop/saving/FrameStatesManagerTest.java
> +        Assert.assertEquals(gameWindow.isIcon(), gameWindow.isIcon());
В этих тестах - проверки хорошие

2024-03-26 04:31 UTC, vpyzhyanov commented on src/main/java/course/oop/saving/FrameConfig.java
> +    public FrameConfig() {
неиспользуемый конструктор

2024-03-26 04:31 UTC, vpyzhyanov commented on src/main/java/course/oop/saving/FrameConfig.java
> +        isIcon = false;
дублирование кода, должен вызываться конструктор этого класса

2024-03-26 04:31 UTC, vpyzhyanov commented on src/main/java/course/oop/saving/FrameConfig.java
> +        this.location = new Pair(location);
дублирование кода, должен вызываться конструктор этого класса

2024-03-26 14:57 UTC, Fenya2 commented on src/test/java/course/oop/saving/FrameStatesManagerTest.java
> +        is.close();
Испавил

2024-03-26 14:57 UTC, Fenya2 commented on src/main/java/course/oop/saving/FrameConfig.java
> +    public FrameConfig() {
Убрал

2024-03-26 14:57 UTC, Fenya2 commented on src/main/java/course/oop/saving/FrameConfig.java
> +        isIcon = false;
Убрал пустой конструктор

2024-03-26 14:57 UTC, Fenya2 commented on src/main/java/course/oop/saving/FrameConfig.java
> +        this.location = new Pair(location);
Сделал

2024-03-26 15:07 UTC, Fenya2 commented
Убрал пустой конструктор, дублирование кода в конструкторах. Дописал гарантированное закрытие потоков в тесте

2024-03-29 03:13 UTC, Fenya2 commented on src/main/java/course/oop/saving/FrameConfig.java
> +     * Геттер
Исправил

2024-03-31 18:31 UTC, vpyzhyanov commented on src/main/java/course/oop/saving/FrameStatesManager.java
> +public class FrameStatesManager implements FrameSaver, FrameLoader {
Не исправлено

2024-03-31 18:34 UTC, vpyzhyanov commented
Дмитрий, почему вы не исправили интерфейсы? Это важно для ООП.

Как исправите, можете мёрджить

2024-03-31 18:45 UTC, Fenya2 commented on src/main/java/course/oop/saving/FrameStatesManager.java
> +public class FrameStatesManager implements FrameSaver, FrameLoader {
Я же их использую (в MainApplicationFrame). Это может быть удобно для класса FrameStatesManager, чтобы ограничить его функциональность в рамках задачи (как, например, есть структуры, которые могут вести себя как очереди и стеки, но в контексте задачи необходимо какое-то одно поведение). Или, например, если загружать/сохранять состояния окон придется из другого места (сеть, бд), то классу/ам, которые делают это, достаточно будет реализовать соответсвующий интерфейс/интерфейсы

2024-03-31 19:16 UTC, Fenya2 commented
Исправил

2024-03-31 19:16 UTC, merged