Task5
Fenya2/Robots_OOP_Course pull request #7
Opened 2024-05-12 20:28 UTC by Fenya2

Написал 5 задачу. В статическом классе (можно оставить статический? Или сделать синглтон? Или есть другое решение?) UserLocaleManager хранится текущий язык пользователя (локаль). По ней подгружается нужный ResourceBundle из соответствующего .properties файла. При смене языка главное окно уничтожается, пересоздается новое с выбранным языком. Ресурсы (ResourceBundle) кэшируются при вызове getBundle()

В LogWindow хранится объект MessageFormat для создания строки лога (сохраняю в кэше объект MessageFormat (Это же оно??))

2024-05-13 19:07 UTC, vpyzhyanov commented
> . В статическом классе (можно оставить статический? Или сделать синглтон? Или есть другое решение?) UserLocaleManager хранится текущий язык пользователя (локаль)

О ужас, статический класс. Докатились( Конечно синглтон, он тут идеально по смыслу подходит. Только один класс в системе должен управлять текущей локалью. На крайний случай могли сделать простой класс и передавать его везде, хоть это менее удобно и появляется возможность создать несколько экземпляров. А статика - это лютое зло, которая сыграет с вами злую шутку при неправильном использовании.

2024-05-13 19:18 UTC, vpyzhyanov commented
> В LogWindow хранится объект MessageFormat для создания строки лога (сохраняю в кэше объект MessageFormat (Это же оно??))

Оно что? Дописывайте, пожалуйста, предложения до конца. Если вы про кеширование, то нет это не оно

2024-05-13 19:58 UTC, vpyzhyanov requested changes
есть замечания

2024-05-13 19:58 UTC, vpyzhyanov commented on src/main/java/course/oop/gui/GameVisualizer.java
> +                Logger.debug(UserLocaleManager.getCurrentBundle().getString("logger.target_changed_controller"));
если уж делаете статические методы, то делайте их удобными, убирайте лишних посредников `UserLocaleManager.getString("logger.target_changed_controller")`

2024-05-13 19:58 UTC, vpyzhyanov commented on src/main/java/course/oop/gui/GameWindow.java
> +        super(UserLocaleManager.getCurrentBundle().getString("game_window_name"), true, true, true, true);
для имён свойств лучше выбирать имена согласованные с их местами использования. Так их будет удобнее найти и быстрее понять к какому классу они относятся. Например `"GameWindow.title"`, т.к. в классе  GameWindow определяется поле title

2024-05-13 19:58 UTC, vpyzhyanov commented on src/main/java/course/oop/gui/LogWindow.java
> +            content.append(logEntryFormatter.format(args)).append("\n");
почему кеширование делать не стали?

2024-05-13 19:58 UTC, vpyzhyanov commented on src/main/java/course/oop/gui/MainApplicationFrame.java
> +            e.printStackTrace();
всегда прошу писать человекочитаемые сообщения об ошибках. И обязательно выводить информацию об исключении

2024-05-13 19:58 UTC, vpyzhyanov commented on src/main/java/course/oop/gui/MainApplicationFrame.java
> +    public void saveWindowStates() {
На каком основании открыт доступ? Пока не вижу необходимости в таком действии. Вижу только нарушение инкапсуляции.

2024-05-13 19:58 UTC, vpyzhyanov commented on src/main/java/course/oop/gui/MainApplicationFrame.java
> -            e.printStackTrace();
почему убрали? Без стека вам будет крайне трудно понять что пошло нет так

2024-05-13 19:58 UTC, vpyzhyanov commented on src/main/java/course/oop/gui/MainMenuBar.java
> +                mainFrame.saveWindowStates();
более правильно будет вызывать это действие перед dispose. Для этого можно переопределить dispose в `MainApplicationFrame`. Тогда инкапсуляцию не будет нарушаться и никто и никогда не забудет сохранить состояние окна перед уничтожением. Вообще-то никто не обязан знать, что окно умеет сохранятся и не забыть вызывать метод сохранения.

**Мудрость:** если можно что-то забыть, то это обязательно будет забыто

2024-05-13 19:58 UTC, vpyzhyanov commented on src/main/java/course/oop/gui/MainMenuBar.java
> +     *
похоже вам что-то помешало дописать JavaDoc)

2024-05-13 19:58 UTC, vpyzhyanov commented on src/main/java/course/oop/gui/MainMenuBar.java
> +                Logger.debug(UserLocaleManager.getCurrentBundle().getString("log.change_lang"));
`bundle` есть в контексте. Не надо его заново запрашивать

2024-05-13 19:58 UTC, vpyzhyanov commented on src/main/java/course/oop/locale/UserLocale.java
> +    RU, // русская
Используйте JavaDoc. Он тут тоже работает

2024-05-13 19:58 UTC, vpyzhyanov commented on src/main/java/course/oop/locale/UserLocaleManager.java
> +    private static File userLocaleFile = new File(
О нет, изменяемое статическое поле. Помянем ООП и принципы SOLID ((((

2024-05-13 19:58 UTC, vpyzhyanov commented on src/main/java/course/oop/locale/UserLocaleManager.java
> +    private static UserLocale currentUserLocale;
аналогично, помянем

2024-05-13 19:58 UTC, vpyzhyanov commented on src/main/java/course/oop/locale/UserLocaleManager.java
> +    static {
статический блок, жуть

2024-05-13 19:58 UTC, vpyzhyanov commented on src/main/java/course/oop/locale/UserLocaleManager.java
> +                new OutputStreamWriter(new FileOutputStream(userLocaleFile), "UTF-8"))) {
`StandardCharsets.UTF_8`

2024-05-13 19:58 UTC, vpyzhyanov commented on src/main/java/course/oop/locale/UserLocaleManager.java
> +            System.err.println("can't create directories to localeFile");
директорию создать не удалось, но мы всё равно будем продолжать выполнение..... это называется "отсутствие отказоустойчивости"

2024-05-13 19:58 UTC, vpyzhyanov commented on src/main/java/course/oop/locale/UserLocaleManager.java
> +    public static synchronized void setUserLocale(UserLocale userLocale) {
зачем синхронизация?

2024-05-13 19:58 UTC, vpyzhyanov commented on src/main/java/course/oop/locale/UserLocaleManager.java
> +            System.err.println("can't save user locale");
а где стек?

2024-05-13 19:58 UTC, vpyzhyanov commented on src/main/java/course/oop/locale/UserLocaleManager.java
> +    private static UserLocale getUserLocaleFromLocaleFile() {
что-то этот класс взял на себя слишком много. Он и текущую локаль определяет и бандлы раздаёт и из файла читает. Не много ли обязанностей? Добро пожаловать на тёмную сторону))

2024-05-13 19:58 UTC, vpyzhyanov commented on src/main/java/course/oop/locale/UserLocaleManager.java
> +            System.err.println("locale file is not exist.");
вот не факт. А что произошло на самом деле вы никогда не узнаете, ведь вы не выводите стек и сообщение об ошибке

2024-05-13 20:04 UTC, vpyzhyanov commented on src/main/java/course/oop/gui/MainMenuBar.java
> +     * Старое чистится сборщиком мусора и уходит с миром.
Правда? Точно? Что-то мне подсказывает, что они не упокоятся с миром и будут ходить в виде зомби или скелетов. Скорее скелетов, т.к. тело вы сожгли. Это не точно, но кажется, что `MainMenuBar` держит `MainApplicationFrame`, т.к. хранит прямую ссылку на него. И наоборот, т.к. основное окно содержит меню.

2024-05-14 04:55 UTC, vpyzhyanov commented on src/main/java/course/oop/gui/LogWindow.java
> +            content.append(logEntryFormatter.format(args)).append("\n");
Вспомнил, что вы спрашивали про классы, которые умеют сами себя кешировать. Вот только `MessageFormat` этого не делает. В этом задание и состоит, чтобы сделать кеширование самому. Даже если бы это работало, то переключение языков у вас некорректно работало бы (в кеше оставались записи на другом языке).

2024-05-14 13:42 UTC, Fenya2 commented on src/main/java/course/oop/gui/GameVisualizer.java
> +                Logger.debug(UserLocaleManager.getCurrentBundle().getString("logger.target_changed_controller"));
Поменял на синглтон. Определил в нем getString(), как у ResourceBundle (вроде фильтра)

2024-05-14 13:42 UTC, Fenya2 commented on src/main/java/course/oop/gui/GameWindow.java
> +        super(UserLocaleManager.getCurrentBundle().getString("game_window_name"), true, true, true, true);
Поменял ключи в файле свойств

2024-05-14 13:42 UTC, Fenya2 commented on src/main/java/course/oop/gui/LogWindow.java
> +            content.append(logEntryFormatter.format(args)).append("\n");
Формально шаблонизатор кешируется в поле класса. Записи лога нужно шешировать тоже?

2024-05-14 13:43 UTC, Fenya2 commented on src/main/java/course/oop/gui/MainApplicationFrame.java
> +            e.printStackTrace();
Написал

2024-05-14 13:43 UTC, Fenya2 commented on src/main/java/course/oop/gui/MainApplicationFrame.java
> +    public void saveWindowStates() {
Переопределил метод dispose(), вернул модификатор доступа private

2024-05-14 13:43 UTC, Fenya2 commented on src/main/java/course/oop/gui/MainApplicationFrame.java
> -            e.printStackTrace();
Вернул вывод стека вызовов

2024-05-14 13:43 UTC, Fenya2 commented on src/main/java/course/oop/gui/MainMenuBar.java
> +                mainFrame.saveWindowStates();
Да. Точно, можно же переопределить dispose()

2024-05-14 13:44 UTC, Fenya2 commented on src/main/java/course/oop/gui/MainMenuBar.java
> +     *
Дописал

2024-05-14 13:44 UTC, Fenya2 commented on src/main/java/course/oop/gui/MainMenuBar.java
> +                Logger.debug(UserLocaleManager.getCurrentBundle().getString("log.change_lang"));
Теперь используется синглтон

2024-05-14 13:44 UTC, Fenya2 commented on src/main/java/course/oop/locale/UserLocale.java
> +    RU, // русская
Точно, добавил

2024-05-14 13:44 UTC, Fenya2 commented on src/main/java/course/oop/locale/UserLocaleManager.java
> +    private static File userLocaleFile = new File(
Убрал

2024-05-14 13:44 UTC, Fenya2 commented on src/main/java/course/oop/locale/UserLocaleManager.java
> +    private static UserLocale currentUserLocale;
Убрал статический класс

2024-05-14 13:44 UTC, Fenya2 commented on src/main/java/course/oop/locale/UserLocaleManager.java
> +    static {
Убрал

2024-05-14 13:44 UTC, Fenya2 commented on src/main/java/course/oop/locale/UserLocaleManager.java
> +                new OutputStreamWriter(new FileOutputStream(userLocaleFile), "UTF-8"))) {
Точно. Так лучше

2024-05-14 13:45 UTC, Fenya2 commented on src/main/java/course/oop/locale/UserLocaleManager.java
> +            System.err.println("can't create directories to localeFile");
Хотя бы на английском чтобы запускалось

2024-05-14 13:46 UTC, Fenya2 commented on src/main/java/course/oop/locale/UserLocaleManager.java
> +    public static synchronized void setUserLocale(UserLocale userLocale) {
Убрал, так как метод всегда вызывается только в одном потоке

2024-05-14 13:46 UTC, Fenya2 commented on src/main/java/course/oop/locale/UserLocaleManager.java
> +            System.err.println("can't save user locale");
Вернул

2024-05-14 13:47 UTC, Fenya2 commented on src/main/java/course/oop/locale/UserLocaleManager.java
> +    private static UserLocale getUserLocaleFromLocaleFile() {
Вынес функции сохранения и загрузки локали в утилитный класс

2024-05-14 13:47 UTC, Fenya2 commented on src/main/java/course/oop/locale/UserLocaleManager.java
> +            System.err.println("locale file is not exist.");
Вернул вывод стека вызовов

2024-05-14 13:48 UTC, Fenya2 commented on src/main/java/course/oop/gui/MainMenuBar.java
> +     * Старое чистится сборщиком мусора и уходит с миром.
Должны упокоится. Окна перестанут быть достижимым после dispose (только по слабым ссылкам)

2024-05-14 14:42 UTC, Fenya2 commented on src/main/java/course/oop/saving/FrameStatesManager.java
> +            } catch (ClassCastException e) {
Я почти уверен, что программа не запустилась, потому что я зыбыл обработать исключение ClassCastException. Судя по сообщение ошибки, там лежал экземпляр java.util.Properties. Сейчас должна запуститься с обработкой исключения и перезаписать файл после выхода

2024-05-14 17:18 UTC, vpyzhyanov commented
Это что за костыль?

![image](https://github.com/Fenya2/Robots_OOP_Course/assets/71599019/33c24a90-6dd1-4d4a-a597-bc4e804252b6)

2024-05-14 18:08 UTC, vpyzhyanov requested changes
Как исправите, можете мёрджить

2024-05-14 18:08 UTC, vpyzhyanov commented on src/main/java/course/oop/locale/LocaleManager.java
> +                return ResourceBundle.getBundle("locales/en", new Locale("en"));
Да, он кешируется, но он ещё делает кучу всяких действий и проверок. Зачем их делать? Особенно когда вы можете их не делать. В любом случае, я бы никогда не ожидал, что метод get будет создавать какие-то объекты каждый раз, я ожидаю, что он просто вернёт мне нужное значение. А ResourceBundle можно менять только при изменении локали.

Естественно вы этого не заметите, у вас очень маленькое приложение и очень маленькая нагрузка.

2024-05-14 18:08 UTC, vpyzhyanov commented on src/main/java/course/oop/locale/LocaleUtils.java
> +class LocaleUtils {
лучше его назвать в соответствии с его назначением. Locale**File**Utils

2024-05-14 18:08 UTC, vpyzhyanov commented on src/main/java/course/oop/locale/LocaleUtils.java
> +            writer.write(locale.toString());
`Files.writeString(...)`

2024-05-14 18:08 UTC, vpyzhyanov commented on src/main/java/course/oop/locale/LocaleManager.java
> +        LocaleUtils.saveLocale(userLocale, userLocaleFile);
я мог бы тут написать, что ответственность по хранению локали находится в двух классах сразу, т.к. ни в имени класса, ни в имени метода ничего про файл не сказано.

2024-05-14 18:08 UTC, vpyzhyanov commented on src/main/java/course/oop/gui/GameVisualizer.java
> +                Logger.debug(LocaleManager.getInstance().getString("logger.target_changed_controller"));
можно было проще `LocaleManager.getString`, а `.getInstance()` можно вызывать внутри метода

2024-05-14 18:08 UTC, vpyzhyanov commented on src/main/java/course/oop/locale/LocaleUtils.java
> +            if (reader.read(buff, 0, 2) != 2) {
`Files.readString(...)`, не мучайтесь больше)

2024-05-14 18:08 UTC, vpyzhyanov commented on src/main/java/course/oop/gui/GameWindow.java
> +        super(UserLocaleManager.getCurrentBundle().getString("game_window_name"), true, true, true, true);
=(  По тексту `game_window` мы не найдём класс (только через текстовый поиск)

2024-05-14 18:08 UTC, vpyzhyanov commented on src/main/java/course/oop/gui/LogWindow.java
> +            content.append(logEntryFormatter.format(args)).append("\n");
Обсудили на паре. Задание выполнено именно в том виде, которое требуется в задании

2024-05-14 18:08 UTC, vpyzhyanov commented on src/main/java/course/oop/locale/UserLocaleManager.java
> +            System.err.println("can't create directories to localeFile");
Нет, вы не поняли. В этой строке не запуск, а **сохранение** файла. Если директорию создать не получилось, то файл записать точно не получится. Можно было сразу выйти.

2024-05-14 18:08 UTC, vpyzhyanov commented on src/main/java/course/oop/locale/LocaleUtils.java
> +            e.printStackTrace();
отсутствие отказоустойчивости не исправлено. Ловим 2 ошибки подряд, хотя можем поймать только одну

2024-05-14 18:08 UTC, vpyzhyanov commented on src/test/java/course/oop/saving/FrameStatesManagerTest.java
>                          // Чтобы не забивать stdout
этот костыль надо убрать

2024-05-14 20:50 UTC, Fenya2 commented on src/test/java/course/oop/saving/FrameStatesManagerTest.java
>                          // Чтобы не забивать stdout
Убрал

2024-05-14 20:50 UTC, Fenya2 commented on src/main/java/course/oop/locale/LocaleUtils.java
> +            e.printStackTrace();
Все, я понял

2024-05-14 20:51 UTC, Fenya2 commented on src/main/java/course/oop/locale/LocaleUtils.java
> +            if (reader.read(buff, 0, 2) != 2) {
Да, так проще. Написал

2024-05-14 20:51 UTC, Fenya2 commented on src/main/java/course/oop/gui/GameVisualizer.java
> +                Logger.debug(LocaleManager.getInstance().getString("logger.target_changed_controller"));
Да. Написал удобный статический метод

2024-05-14 20:51 UTC, Fenya2 commented on src/main/java/course/oop/locale/LocaleManager.java
> +        LocaleUtils.saveLocale(userLocale, userLocaleFile);
Переименовал метод

2024-05-14 20:51 UTC, Fenya2 commented on src/main/java/course/oop/locale/LocaleUtils.java
> +            writer.write(locale.toString());
Да, так проще. Поменял

2024-05-14 20:51 UTC, Fenya2 commented on src/main/java/course/oop/locale/LocaleUtils.java
> +class LocaleUtils {
Переименовал

2024-05-14 20:52 UTC, Fenya2 commented on src/main/java/course/oop/locale/LocaleManager.java
> +                return ResourceBundle.getBundle("locales/en", new Locale("en"));
Сохраняю возвращаемы getBundle() ResourceBundle в поле синглтона

2024-05-14 20:53 UTC, Fenya2 commented
Исправил

2024-05-14 20:55 UTC, merged